### ISSUE TITLE
Javascript error: "invalid group specifier name"

### ISSUE THREAD

**Issue by andypullen** [verbb/smith#8] opened 2020-07-24 16:33 UTC
### Description
Smith is throwing a javascript error – `Invalid regular expression: invalid group specifier name` which is causing a jquery TypeError: `undefined is not an object (evaluating 'new Craft.Smith.Init')`. This is causing the matrix blocks to not finish rendering and the inability to add new blocks.

### Steps to reproduce

1. Open an edit or new Entry page containing a matrix blocks field.

### Additional info

- Plugin version: 1.1.4
- Craft version: 3.4.29.1

**Comment by engram-design** [comment] 2020-07-26 12:39
Looks like this is an issue in Safari? Should be fixed in [1.1.5](https://github.com/verbb/smith/releases/tag/1.1.5)

**Closed as completed by engram-design** 2020-07-26 12:39 UTC

**Comment by andypullen** [comment] 2020-07-26 13:27
I can't believe I didn't test in other browsers! Thanks for catching that. 🍻

**Comment by engram-design** [comment] 2020-07-26 13:31
All good, I honestly was about to send a response back saying I couldn't reproduce as I tried all other browsers except Safari. Seems like that was the only one with the issue 👍
