### ISSUE TITLE
Clone Product Variations support

### ISSUE THREAD

**Issue by wmdhosting** [verbb/smith#35] opened 2024-01-14 07:44 UTC
### What are you trying to do?

I know its not related to matrix. but will be great to have if posiblle  ability to **CLONE** **Product Variations**
same way as matrix works.

### What's your proposed solution?

Just add Clone option to Product variations

**Comment by engram-design** [comment] 2024-01-14 08:00
Duplicate of https://github.com/verbb/smith/issues/2

**Closed as completed by engram-design** 2024-01-14 08:00 UTC
Labels: feature request
